[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.1"
  export = ["echo_service"]
  keywords = ["Type/RestApi","Category/Service","Internal/http"]
  name = "echo_service"
  org = "mariawso2"
  version = "1.1.0"